name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Create wrangler.toml
        run: |
          cat > wrangler.toml <<EOF
          name = "url-shortener-gitops"
          type = "webpack"
          account_id = "${{ secrets.CF_ACCOUNT_ID }}"
          workers_dev = true
          route = "link.haenu.com/*"
          EOF
      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
